const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const serviceWorkerDir = path.resolve(__dirname, '../public');

function getGitVersion() {
    try {
        // Use a clean version for production, without --dirty
        const version = execSync('git describe --tags --always').toString().trim();
        return version;
    } catch (error) {
        console.error('❌ Error getting git version:', error.message);
        return 'unknown-version'; // Fallback
    }
}

const appVersion = getGitVersion();
const content = `// This file is auto-generated by the build process.\nexport const APP_VERSION = "${appVersion}";\n`;
const outputPath = path.join(serviceWorkerDir, 'app-version.js'); // Separate file for version

try {
    fs.writeFileSync(outputPath, content);
    console.log(`✨ App version "${appVersion}" written to ${outputPath}`);
} catch (error) {
    console.error(`❌ Failed to write version file: ${error.message}`);
    process.exit(1); // Exit with an error if file writing fails
}